# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heinsight/vision/folder_of_images_to_video_converter_gui/folder_of_images_to_video_converter_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 362)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setText("Convert a folder of images into a video")
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 511, 220))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.General_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.General_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.General_groupBox.setObjectName("General_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.General_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.output_video_file_format_comboBox = QtWidgets.QComboBox(self.General_groupBox)
        self.output_video_file_format_comboBox.setObjectName("output_video_file_format_comboBox")
        self.output_video_file_format_comboBox.addItem("")
        self.output_video_file_format_comboBox.addItem("")
        self.gridLayout.addWidget(self.output_video_file_format_comboBox, 5, 1, 1, 1)
        self.output_video_file_location_label = QtWidgets.QLabel(self.General_groupBox)
        self.output_video_file_location_label.setObjectName("output_video_file_location_label")
        self.gridLayout.addWidget(self.output_video_file_location_label, 4, 0, 1, 1)
        self.output_video_file_format_label = QtWidgets.QLabel(self.General_groupBox)
        self.output_video_file_format_label.setObjectName("output_video_file_format_label")
        self.gridLayout.addWidget(self.output_video_file_format_label, 5, 0, 1, 1)
        self.folder_of_images_directory_browse_button = QtWidgets.QPushButton(self.General_groupBox)
        self.folder_of_images_directory_browse_button.setObjectName("folder_of_images_directory_browse_button")
        self.gridLayout.addWidget(self.folder_of_images_directory_browse_button, 0, 2, 1, 1)
        self.output_video_file_location_browse_button = QtWidgets.QPushButton(self.General_groupBox)
        self.output_video_file_location_browse_button.setObjectName("output_video_file_location_browse_button")
        self.gridLayout.addWidget(self.output_video_file_location_browse_button, 4, 2, 1, 1)
        self.output_video_fps_label = QtWidgets.QLabel(self.General_groupBox)
        self.output_video_fps_label.setObjectName("output_video_fps_label")
        self.gridLayout.addWidget(self.output_video_fps_label, 3, 0, 1, 1)
        self.output_video_file_location_LineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.output_video_file_location_LineEdit.setObjectName("output_video_file_location_LineEdit")
        self.gridLayout.addWidget(self.output_video_file_location_LineEdit, 4, 1, 1, 1)
        self.folder_of_images_directory_label = QtWidgets.QLabel(self.General_groupBox)
        self.folder_of_images_directory_label.setObjectName("folder_of_images_directory_label")
        self.gridLayout.addWidget(self.folder_of_images_directory_label, 0, 0, 1, 1)
        self.output_video_fps_spinBox = QtWidgets.QSpinBox(self.General_groupBox)
        self.output_video_fps_spinBox.setProperty("value", 30)
        self.output_video_fps_spinBox.setObjectName("output_video_fps_spinBox")
        self.gridLayout.addWidget(self.output_video_fps_spinBox, 3, 1, 1, 1)
        self.folder_of_images_directory_LineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.folder_of_images_directory_LineEdit.setObjectName("folder_of_images_directory_LineEdit")
        self.gridLayout.addWidget(self.folder_of_images_directory_LineEdit, 0, 1, 1, 1)
        self.display_image_name_checkBox = QtWidgets.QCheckBox(self.General_groupBox)
        self.display_image_name_checkBox.setObjectName("display_image_name_checkBox")
        self.gridLayout.addWidget(self.display_image_name_checkBox, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.General_groupBox)
        self.convert_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.convert_pushButton.setObjectName("convert_pushButton")
        self.verticalLayout.addWidget(self.convert_pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HeinSight"))
        self.General_groupBox.setTitle(_translate("MainWindow", "General"))
        self.output_video_file_format_comboBox.setItemText(0, _translate("MainWindow", "mp4"))
        self.output_video_file_format_comboBox.setItemText(1, _translate("MainWindow", "avi"))
        self.output_video_file_location_label.setText(_translate("MainWindow", "Output video file location"))
        self.output_video_file_format_label.setText(_translate("MainWindow", "Output video file format"))
        self.folder_of_images_directory_browse_button.setText(_translate("MainWindow", "Browse..."))
        self.output_video_file_location_browse_button.setText(_translate("MainWindow", "Browse..."))
        self.output_video_fps_label.setText(_translate("MainWindow", "Output video fps"))
        self.folder_of_images_directory_label.setText(_translate("MainWindow", "Input image directory"))
        self.display_image_name_checkBox.setText(_translate("MainWindow", "Display image name on frames"))
        self.convert_pushButton.setText(_translate("MainWindow", "Convert"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))

