# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heinsight/vision/record_images_from_webcam_to_folder_gui/record_images_from_webcam_to_folder_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 433)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setText("Record images from a webcam into a folder")
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.instructions_pt_1_label = QtWidgets.QLabel(self.centralwidget)
        self.instructions_pt_1_label.setWordWrap(True)
        self.instructions_pt_1_label.setObjectName("instructions_pt_1_label")
        self.verticalLayout_5.addWidget(self.instructions_pt_1_label)
        self.instructions_pt_2_label = QtWidgets.QLabel(self.centralwidget)
        self.instructions_pt_2_label.setWordWrap(True)
        self.instructions_pt_2_label.setObjectName("instructions_pt_2_label")
        self.verticalLayout_5.addWidget(self.instructions_pt_2_label)
        self.instructions_pt_3_label = QtWidgets.QLabel(self.centralwidget)
        self.instructions_pt_3_label.setWordWrap(True)
        self.instructions_pt_3_label.setObjectName("instructions_pt_3_label")
        self.verticalLayout_5.addWidget(self.instructions_pt_3_label)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 528, 160))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.General_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.General_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.General_groupBox.setObjectName("General_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.General_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.save_folder_location_browse_button = QtWidgets.QPushButton(self.General_groupBox)
        self.save_folder_location_browse_button.setObjectName("save_folder_location_browse_button")
        self.gridLayout.addWidget(self.save_folder_location_browse_button, 0, 2, 1, 1)
        self.save_folder_location_LineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.save_folder_location_LineEdit.setObjectName("save_folder_location_LineEdit")
        self.gridLayout.addWidget(self.save_folder_location_LineEdit, 0, 1, 1, 1)
        self.save_folder_location_label = QtWidgets.QLabel(self.General_groupBox)
        self.save_folder_location_label.setObjectName("save_folder_location_label")
        self.gridLayout.addWidget(self.save_folder_location_label, 0, 0, 1, 1)
        self.camera_port_label = QtWidgets.QLabel(self.General_groupBox)
        self.camera_port_label.setObjectName("camera_port_label")
        self.gridLayout.addWidget(self.camera_port_label, 1, 0, 1, 1)
        self.camera_port_spinBox = QtWidgets.QSpinBox(self.General_groupBox)
        self.camera_port_spinBox.setMaximum(5)
        self.camera_port_spinBox.setObjectName("camera_port_spinBox")
        self.gridLayout.addWidget(self.camera_port_spinBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.General_groupBox)
        self.start_recording_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.start_recording_pushButton.setObjectName("start_recording_pushButton")
        self.verticalLayout.addWidget(self.start_recording_pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HeinSight"))
        self.instructions_pt_1_label.setText(_translate("MainWindow", "Select a folder to save the images that will be captured by the camera into."))
        self.instructions_pt_2_label.setText(_translate("MainWindow", "Select the camera port; if there is no internal computer webcam and you have a usb webcam connected, select 0. If there is an internal webcam and you want to connect to a usb webcam, select 1."))
        self.instructions_pt_3_label.setText(_translate("MainWindow", "After you press the \"Start recording\" button, to stop recording press the \"q\" button on the keyboard. To turn the folder of images into a video, use the folder of images to video GUI."))
        self.General_groupBox.setTitle(_translate("MainWindow", "General"))
        self.save_folder_location_browse_button.setText(_translate("MainWindow", "Browse..."))
        self.save_folder_location_label.setText(_translate("MainWindow", "Folder to save images to"))
        self.camera_port_label.setText(_translate("MainWindow", "Camera port"))
        self.start_recording_pushButton.setText(_translate("MainWindow", "Start recording"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))

