# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heinsight/liquidlevel/liquid_level_data_analysis_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 665)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setText("Liquid level data analysis")
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 482))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.General_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.General_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.General_groupBox.setObjectName("General_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.General_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.output_file_location_browse_button = QtWidgets.QPushButton(self.General_groupBox)
        self.output_file_location_browse_button.setObjectName("output_file_location_browse_button")
        self.gridLayout.addWidget(self.output_file_location_browse_button, 9, 2, 1, 1)
        self.output_file_location_label = QtWidgets.QLabel(self.General_groupBox)
        self.output_file_location_label.setObjectName("output_file_location_label")
        self.gridLayout.addWidget(self.output_file_location_label, 9, 0, 1, 1)
        self.liquid_level_data_browse_button = QtWidgets.QPushButton(self.General_groupBox)
        self.liquid_level_data_browse_button.setObjectName("liquid_level_data_browse_button")
        self.gridLayout.addWidget(self.liquid_level_data_browse_button, 6, 2, 1, 1)
        self.output_file_location_LineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.output_file_location_LineEdit.setObjectName("output_file_location_LineEdit")
        self.gridLayout.addWidget(self.output_file_location_LineEdit, 9, 1, 1, 1)
        self.output_video_file_format_comboBox = QtWidgets.QComboBox(self.General_groupBox)
        self.output_video_file_format_comboBox.setObjectName("output_video_file_format_comboBox")
        self.output_video_file_format_comboBox.addItem("")
        self.gridLayout.addWidget(self.output_video_file_format_comboBox, 10, 1, 1, 1)
        self.relative_x_axis_checkBox = QtWidgets.QCheckBox(self.General_groupBox)
        self.relative_x_axis_checkBox.setObjectName("relative_x_axis_checkBox")
        self.gridLayout.addWidget(self.relative_x_axis_checkBox, 2, 0, 1, 1)
        self.output_file_format_label = QtWidgets.QLabel(self.General_groupBox)
        self.output_file_format_label.setObjectName("output_file_format_label")
        self.gridLayout.addWidget(self.output_file_format_label, 10, 0, 1, 1)
        self.datetime_format_label = QtWidgets.QLabel(self.General_groupBox)
        self.datetime_format_label.setObjectName("datetime_format_label")
        self.gridLayout.addWidget(self.datetime_format_label, 8, 0, 1, 1)
        self.x_axis_label_label = QtWidgets.QLabel(self.General_groupBox)
        self.x_axis_label_label.setObjectName("x_axis_label_label")
        self.gridLayout.addWidget(self.x_axis_label_label, 1, 0, 1, 1)
        self.relative_x_axis_units_comboBox = QtWidgets.QComboBox(self.General_groupBox)
        self.relative_x_axis_units_comboBox.setEnabled(False)
        self.relative_x_axis_units_comboBox.setObjectName("relative_x_axis_units_comboBox")
        self.relative_x_axis_units_comboBox.addItem("")
        self.relative_x_axis_units_comboBox.addItem("")
        self.relative_x_axis_units_comboBox.addItem("")
        self.gridLayout.addWidget(self.relative_x_axis_units_comboBox, 2, 1, 1, 1)
        self.graph_title_lineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.graph_title_lineEdit.setObjectName("graph_title_lineEdit")
        self.gridLayout.addWidget(self.graph_title_lineEdit, 0, 1, 1, 1)
        self.graph_title_label = QtWidgets.QLabel(self.General_groupBox)
        self.graph_title_label.setObjectName("graph_title_label")
        self.gridLayout.addWidget(self.graph_title_label, 0, 0, 1, 1)
        self.y_axis_type_label = QtWidgets.QLabel(self.General_groupBox)
        self.y_axis_type_label.setObjectName("y_axis_type_label")
        self.gridLayout.addWidget(self.y_axis_type_label, 4, 0, 1, 1)
        self.liquid_level_data_LineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.liquid_level_data_LineEdit.setObjectName("liquid_level_data_LineEdit")
        self.gridLayout.addWidget(self.liquid_level_data_LineEdit, 6, 1, 1, 1)
        self.y_axis_increment_label = QtWidgets.QLabel(self.General_groupBox)
        self.y_axis_increment_label.setObjectName("y_axis_increment_label")
        self.gridLayout.addWidget(self.y_axis_increment_label, 5, 0, 1, 1)
        self.y_axis_label_label = QtWidgets.QLabel(self.General_groupBox)
        self.y_axis_label_label.setObjectName("y_axis_label_label")
        self.gridLayout.addWidget(self.y_axis_label_label, 3, 0, 1, 1)
        self.liquid_level_data_label = QtWidgets.QLabel(self.General_groupBox)
        self.liquid_level_data_label.setObjectName("liquid_level_data_label")
        self.gridLayout.addWidget(self.liquid_level_data_label, 6, 0, 1, 1)
        self.y_axis_type_comboBox = QtWidgets.QComboBox(self.General_groupBox)
        self.y_axis_type_comboBox.setObjectName("y_axis_type_comboBox")
        self.y_axis_type_comboBox.addItem("")
        self.y_axis_type_comboBox.addItem("")
        self.gridLayout.addWidget(self.y_axis_type_comboBox, 4, 1, 1, 1)
        self.y_axis_label_lineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.y_axis_label_lineEdit.setObjectName("y_axis_label_lineEdit")
        self.gridLayout.addWidget(self.y_axis_label_lineEdit, 3, 1, 1, 1)
        self.x_axis_label_lineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.x_axis_label_lineEdit.setObjectName("x_axis_label_lineEdit")
        self.gridLayout.addWidget(self.x_axis_label_lineEdit, 1, 1, 1, 1)
        self.y_axis_increment_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.General_groupBox)
        self.y_axis_increment_doubleSpinBox.setEnabled(True)
        self.y_axis_increment_doubleSpinBox.setMaximum(999.0)
        self.y_axis_increment_doubleSpinBox.setProperty("value", 1.0)
        self.y_axis_increment_doubleSpinBox.setObjectName("y_axis_increment_doubleSpinBox")
        self.gridLayout.addWidget(self.y_axis_increment_doubleSpinBox, 5, 1, 1, 1)
        self.datetime_format_lineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.datetime_format_lineEdit.setObjectName("datetime_format_lineEdit")
        self.gridLayout.addWidget(self.datetime_format_lineEdit, 8, 1, 1, 1)
        self.reference_image_label = QtWidgets.QLabel(self.General_groupBox)
        self.reference_image_label.setObjectName("reference_image_label")
        self.gridLayout.addWidget(self.reference_image_label, 7, 0, 1, 1)
        self.reference_image_lineEdit = QtWidgets.QLineEdit(self.General_groupBox)
        self.reference_image_lineEdit.setObjectName("reference_image_lineEdit")
        self.gridLayout.addWidget(self.reference_image_lineEdit, 7, 1, 1, 1)
        self.reference_image_browse_button = QtWidgets.QPushButton(self.General_groupBox)
        self.reference_image_browse_button.setObjectName("reference_image_browse_button")
        self.gridLayout.addWidget(self.reference_image_browse_button, 7, 2, 1, 1)
        self.verticalLayout.addWidget(self.General_groupBox)
        self.generate_file_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.generate_file_pushButton.setObjectName("generate_file_pushButton")
        self.verticalLayout.addWidget(self.generate_file_pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Liquid level data analysis"))
        self.General_groupBox.setTitle(_translate("MainWindow", "General"))
        self.output_file_location_browse_button.setText(_translate("MainWindow", "Browse..."))
        self.output_file_location_label.setText(_translate("MainWindow", "Output file location"))
        self.liquid_level_data_browse_button.setText(_translate("MainWindow", "Browse..."))
        self.output_video_file_format_comboBox.setItemText(0, _translate("MainWindow", "png"))
        self.relative_x_axis_checkBox.setText(_translate("MainWindow", "Relative X axis"))
        self.output_file_format_label.setText(_translate("MainWindow", "Output file format"))
        self.datetime_format_label.setText(_translate("MainWindow", "Date time format"))
        self.x_axis_label_label.setText(_translate("MainWindow", "X axis label"))
        self.relative_x_axis_units_comboBox.setItemText(0, _translate("MainWindow", "seconds"))
        self.relative_x_axis_units_comboBox.setItemText(1, _translate("MainWindow", "minutes"))
        self.relative_x_axis_units_comboBox.setItemText(2, _translate("MainWindow", "hours"))
        self.graph_title_label.setText(_translate("MainWindow", "Graph title"))
        self.y_axis_type_label.setText(_translate("MainWindow", "Y axis type"))
        self.y_axis_increment_label.setText(_translate("MainWindow", "Y axis increment"))
        self.y_axis_label_label.setText(_translate("MainWindow", "Y axis label"))
        self.liquid_level_data_label.setText(_translate("MainWindow", "Input data JSON file"))
        self.y_axis_type_comboBox.setItemText(0, _translate("MainWindow", "Constantly increasing Y value"))
        self.y_axis_type_comboBox.setItemText(1, _translate("MainWindow", "Liquid level"))
        self.datetime_format_lineEdit.setText(_translate("MainWindow", "%Y_%m_%d_%H_%M_%S"))
        self.reference_image_label.setText(_translate("MainWindow", "Reference image"))
        self.reference_image_browse_button.setText(_translate("MainWindow", "Browse..."))
        self.generate_file_pushButton.setText(_translate("MainWindow", "Generate file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Generate time course graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Tab 2"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))

